[tool.poetry]
name = "same-mono-private"
version = "0.1.0"
description = ""
authors = ["David Aronchick <aronchick@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
click = "^8.0.1"
pytest-virtualenv = "^1.7.0"
"ruamel.yaml" = "^0.17.16"
jupytext = "^1.11.5"

[tool.poetry.dev-dependencies]
pip-tools = "^6.2.0"
pytest = "^6.2.5"
pytest-cov = "^2.12.1"
black = {version = "^21.8b0", allow-prereleases = true}
flake8 = "^3.9.2"
ipython = "^7.27.0"
mock = "^4.0.3"
pytest-virtualenv = "^1.7.0"
johnnydep = "^1.8"

[tool.black]
line-length = 119

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
