[tool.poetry]
name = "same-mono-private"
version = "0.1.0"
description = ""
authors = ["David Aronchick <aronchick@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
click = "^8.0.1"
flake8 = "^3.9.2"

[tool.poetry.dev-dependencies]
pip-tools = "^6.2.0"
pylint = "^2.10.2"
pytest = "^6.2.5"
pytest-cov = "^2.12.1"
black = {version = "^21.8b0", allow-prereleases = true}
flake8 = "^3.9.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
