name: Labeler
on:
  pull_request_target:
    branches:
      - main

jobs:
  label:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/labeler@v4
      with:
        repo-token: ${{github.token}}
