name: Pull Requests
on:
  # internal PRs need no trigger:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  # external PRs need a label to trigger them:
  pull_request_target:
    branches:
      - main
    types:
      - labeled
jobs:
  # only runs for pushes and non-fork pull requests
  Internal:
    uses: ./.github/workflows/tests.yaml
    with:
      sha: ${{ github.ref }}
    if: ${{ github.event_name == 'push' || (github.event_name == 'pull_request' && ! github.event.pull_request.head.repo.fork) }}

  # only runs for forked pull requests
  External:
    uses: ./.github/workflows/tests.yaml
    with:
      sha: ${{ github.event.pull_request.head.sha }}
    if: ${{ github.event_name == 'pull_request_target' && github.event.pull_request.head.repo.fork && contains(github.event.pull_request.labels.*.name, 'ok-to-test') }}
