name: Pull Requests
on:
  # internal PRs need no trigger:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  # external PRs need a label to trigger them:
  pull_request_target:
    branches:
      - main
    types:
      - labeled
jobs:
  # only runs for pushes and non-fork pull requests
  Internal:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || (github.event_name == 'pull_request' && ! github.event.pull_request.head.repo.fork) }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/tests.yaml
        with:
          git-token: ${{ github.token }}
          git-sha: ${{ github.ref }}

  # only runs for forked pull requests
  External:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request_target' && github.event.pull_request.head.repo.fork && contains(github.event.pull_request.labels.*.name, 'ok-to-test') }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/tests.yaml
        with:
          git-token: ${{ github.token }}
          git-sha: ${{ github.event.pull_request.head.sha }}
